requires 'perl', '5.008001';
requires 'strict';
requires 'warnings';
requires 'utf8';

on test => sub {
	requires 'Data::Dumper';
	requires 'Test::More';
	requires 'constant';
	requires 'if';
	requires 'open';
};

# vim: ft=perl
